### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by gabriel-ecegi** [tatumio/tatum-csharp#24]
Hello,
READ.ME looks broken.
1.)
There is no image on the top.
![image](https://user-images.githubusercontent.com/35489017/143606825-ffb11822-fe8e-44c5-ab5c-cb471db97616.png)

2.)
Which nuget is the right one?
![image](https://user-images.githubusercontent.com/35489017/143607147-f372a64f-455d-423b-803f-fdb3d5085241.png)

Stats are linked to: https://www.nuget.org/packages/Tatum/1.2.0?_src=template
Link is for the nuget: https://www.nuget.org/packages/TatumCS/

**Comment by Smrecz** [comment]
C# SDK v2 is out - closing all the issues for v1 cause they are not relevant any more.
