### ISSUE TITLE
Error in Wallet.cs

### ISSUE THREAD

**Issue by alagabaer** [tatumio/tatum-csharp#29]
Please fix line 38 and 57 ff

 case Currency.ETH:

 case Currency.CELO:
                    IEthereumClient ethereumClient = new EthereumClient("");
                    return ethereumClient.CreateWallet(mnemonic, testnet);

**Comment by Smrecz** [comment]
C# SDK v2 is out - closing all the issues for v1 cause they are not relevant any more.
