### ISSUE TITLE
How to get some fake currency in test net?

### ISSUE THREAD

**Issue by zydjohnHotmail** [tatumio/tatum-csharp#46]
Hello:
As I am new to this SDK, I have a few questions to ask.
I think if I have a main net wallet address, I can use it to receive real cryptocurrencies, like: BTC, ETH or USDT.
But if I have only test net wallet address, where and how can I get some free or fake currencies, so I can do some testings.
If I have two test net addresses generated by different private key, can I use the test net address to send and receive fake currencies, just for testing to know the process.
Please advise,
Thanks,

**Comment by Smrecz** [comment]
Hello @zydjohnHotmail,
Can we please move the discussion to https://discord.com/channels/847940290903932939/914832388431958036

I'll be able to answer all of your questions related to use cases there. Github issues it more for technical issues with the SDKs and not so well suited for support discussions.

As for the question the testnet currencies are obtainet from testnet faucets. You can find example links to faucets on each blockchain related part of the docs here https://apidoc.tatum.io/
