### ISSUE TITLE
How to get some credits and multi-chain wallet?

### ISSUE THREAD

**Issue by zydjohnHotmail** [tatumio/tatum-csharp#48]
Hello,
I am new to this repo, I read some documents, and I found many API calls
need credits, I am now in free plan, I want to do more testing before I
can subscribe to a paid plan.
So, how can I get some credits to use those API calls which need credits?
Finally, I want to have one wallet, which I can have at least the following
4 network addresses:
Ethereum, BSC, Solana and Tron.
I want to be able to receive cryptos in the multi-chain wallet, and able
to send the cryptos from my wallet to other wallet address.
For example: I want to be able to receive USDT from another address via
Ethereum(ERC20) network, and able to send USDT from my wallet address to anoter
address via BSC(BEP20) network.
Let me know if I can use the repo to do this?
To create multi-chain address wallet which can cross 4 different networks,
how many addresses I have to create?
I think 3 will be enough, right?
One address for both Ethereum and BSC, another one for Solana and yet 
another one for TRON network.
Let me know if I can do this with the repo and if yes, how to proceed.
One final question: how can I find the gas fees before I send cryptos out of my multi-chain wallet?
Thanks

**Comment by Smrecz** [comment]
Hello @zydjohnHotmail,
Can we please move the discussion to https://discord.com/channels/847940290903932939/914832388431958036

I'll be able to answer all of your questions related to use cases there. Github issues it more for technical issues with the SDKs and not so well suited for support discussions.

As for the question the free plan comes with unlimitted credits but you can only make 5 requests per second.

Multi currency wallet needs to be implemented on your side from separate wallets as this SDK is not supporting this scenario at the moment.
